name: Node.js Package

on:
  push:
    branches :
      - master
  
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps :
      - uses: actions/checkout@v2
      - uses: actions/setup-node@vl
        with :
            node-version: 12
            registry-url: https://npa.pkg.github.com/
            scope: "ivAKii"
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
